// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Border } from "./Border";
import type { GalaxyCenter } from "./GalaxyCenter";

export type ObjectiveView = { centers: Array<GalaxyCenter>, active_borders: Array<Border>, inactive_borders: Array<Border>, };
