// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardError } from "./BoardError";
import type { ObjectiveView } from "./ObjectiveView";

/**
 * The parts of the state necessary for rendering
 */
export type StateView = { vertical_borders: Array<Array<boolean>>, horizontal_borders: Array<Array<boolean>>, objective: ObjectiveView, error: BoardError | null, has_future: boolean, has_past: boolean, is_solved: boolean, };
